### PR TITLE
Add Flatpak manifest

### LINKED ISSUE #105: Package as Flatpak for elementary OS 6
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

### PR DESCRIPTION
**Pull request by ryonakano**
Fixes #105

I'm getting the following error message in the terminal:

```
No PulseAudio daemon running, or not running as session daemon.
```

and the error dialog is shown with following message:

```
Failed to connect stream: Invalid argument
../ext/pulse/pulsesrc.c(1619): gst_pulsesrc_prepare (): /GstPipeline:pipeline/GstPulseSrc:mic_sound
```

Also I need to set `$TMPDIR`  as `$XDG_RUNTIME_DIR/app/$FLATPAK_ID` since accessing to the host `/tmp` is not recommended, but not sure how…

### CODE REVIEW

**Comment by SubhadeepJasu** [comment]
I am not getting the pulse audio daemon error in terminal, but I am getting that error dialog box with that same message. Seems to only happen when trying to record from mic. I'll investigate this issue as well.

**Comment by ryonakano** [comment]
@SubhadeepJasu Thank you for your comment!

As far as I investigated, the command `pacmd` is unavailable with the current yaml file and print the "no daemon" error message in the terminal. So I replaced that command with `pactl` which seems similar command, but not sure if the regex pattern properly extract a microphone name—at least it works on my computer, but may not on other environment. So I really appreciate your testing and commitment to this issue. :sob:

**Comment by SubhadeepJasu** [comment]
Update. I got mic working in flatpak by using 
``` Vala
GLib.Regex regex = new Regex ("Name: (.*(?<!monitor)$)", RegexCompileFlags.JAVASCRIPT_COMPAT | RegexCompileFlags.MULTILINE);
```

This is only when not using "SYSTEM". So I have not yet tested "BOTH"

**Comment by ryonakano** [comment]
Thank you for your information!! I'll check if it works on my side too and update the code soon :tada:

**Comment by ryonakano** [comment]
Hi @SubhadeepJasu, thank you very much for your code! It works perfectly :tada: I would really appreciate it.

Regarding to the check of Flatpak, I don't think it needed for this app at the moment because your way to detect microphone works both in Flatpak and a native environment (at least on my PC). Doesn't this way work as expected in a native environment on your PC?

**Comment by SubhadeepJasu** [comment]
For me it didn't so I did that. Well it's a simple logic incase you need it for anything else.

**Comment by ryonakano** [comment]
Hi @SubhadeepJasu, I changed how to detect microphones, would you test if this change works for you both in Flatpak and in the native environemnt?

**Comment by SubhadeepJasu** [comment]
Sure

**Comment by SubhadeepJasu** [comment]
Still getting this 
```Failed to connect stream: Invalid argument
../ext/pulse/pulsesrc.c(1619): gst_pulsesrc_prepare (): /GstPipeline:pipeline/GstPulseSrc:mic_sound```

**Comment by ryonakano** [comment]
Hmm, strange. Would you run the app with `G_MESSAGES_DEBUG=all` environment variable, and paste the output here?

Also, I'd like to know output of `pactl list sources` on your system.

**Comment by SubhadeepJasu** [comment]
```
DeviceManager.vala:75: Device detected: Built-in Audio Analog Stereo, alsa_input.pci-0000_00_1f.3.analog-stereo

** (com.github.ryonakano.reco:2): DEBUG: 11:16:27.193: DeviceManager.vala:75: Device detected: Monitor of Built-in Audio Analog Stereo, alsa_output.pci-0000_00_1f.3.analog-stereo.monitor

(com.github.ryonakano.reco:2): GVFS-RemoteVolumeMonitor-DEBUG: 11:16:27.317: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(com.github.ryonakano.reco:2): GVFS-DEBUG: 11:16:27.318: cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory

Recorder.vala:78: Set source microphone to 
** (com.github.ryonakano.reco:2): DEBUG: 11:17:26.392: Recorder.vala:124: The recording is temporary stored at /tmp/com.github.ryonakano.reco/reco_1626760046.wav

``` plus the above error dialog when recording

**Comment by SubhadeepJasu** [comment]
`pactl list sources` gives:
``` MD
Source #0
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Description: Monitor of Built-in Audio Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor of Sink: alsa_output.pci-0000_00_1f.3.analog-stereo
	Latency: 0 usec, configured 0 usec
	Flags: DECIBEL_VOLUME LATENCY 
	Properties:
		device.description = "Monitor of Built-in Audio Analog Stereo"
		device.class = "monitor"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xb4328000 irq 134"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1f.3"
		sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "9d71"
		device.product.name = "Sunrise Point-LP HD Audio"
		device.form_factor = "internal"
		device.string = "0"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Formats:
		pcm

Source #1
	State: SUSPENDED
	Name: alsa_input.pci-0000_00_1f.3.analog-stereo
	Description: Built-in Audio Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 21892 /  33% / -28.57 dB,   front-right: 21892 /  33% / -28.57 dB
	        balance 0.00
	Base Volume: 6554 /  10% / -60.00 dB
	Monitor of Sink: n/a
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "ALC295 Analog"
		alsa.id = "ALC295 Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xb4328000 irq 134"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1f.3"
		sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "9d71"
		device.product.name = "Sunrise Point-LP HD Audio"
		device.form_factor = "internal"
		device.string = "front:0"
		device.buffering.buffer_size = "352800"
		device.buffering.fragment_size = "176400"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Analog Stereo"
		device.description = "Built-in Audio Analog Stereo"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Ports:
		analog-input-internal-mic: Internal Microphone (priority: 8900)
		analog-input-mic: Microphone (priority: 8700, not available)
	Active Port: analog-input-internal-mic
	Formats:
		pcm
```

**Comment by ryonakano** [comment]
Thank you for your information! Now it should work as expected…🤔

**Comment by ryonakano** [comment]
Glad to hear that 😊

**Comment by ryonakano** [comment]
Merging the PR, thank you very much for your help @SubhadeepJasu!

**Pull request merged**
