### PR TITLE
Add french translations

### PR DESCRIPTION
**Pull request by NathanBnm**

### CODE REVIEW

**Comment by ryonakano** [comment]
@NathanBnm Hi, thank you for your translation! Your translation for the app itself looks good to me, but I also would like you to translate strings in the .desktop and .appdata.xml file. I prepared `po/extra/extra.pot` for these translations, so please generate `po/extra/fr.po` by using ninja command or copying `po/extra/extra.pot`, translate strings in that file, and add that file to this PR. (Also add edited `po/extra/LINGUAS`)

**Comment by NathanBnm** [comment]
@ryonakano why did you separe theses translations in different files ? You could also keep those in the main file at the beginning or at the end. But the changes are committed ;)

**Comment by ryonakano** [comment]
@NathanBnm Thank you for translating the extra po file too! I separated because the elementary developers do this. Also, I think this allows translators to know strings they're translating appear whether in code files or in other files easily. I don't know the actual reason why elementary developers do though…

**Comment by NathanBnm** [comment]
You're welcome, and that's okay I understand. I noticed that because others app developers don't do this. But you're right, better to do like the elementary developers I mean.

**Pull request merged**
