### PR TITLE
Handle large indexes

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #80

### CODE REVIEW

**Comment by peteruithoven** [comment]
Just tested this and it seems to generate this error:
```
Error while compiling regular expression (?<=\*\sindex:\s\d+\s\sname:\s<)[\w\.\-]* at char 31: lookbehind assertion is not fixed length
```

**Comment by peteruithoven** [comment]
Fixed by removing the lookbehind and using a capturing group. 

Regex test: https://regex101.com/r/BiCX4v/1

**Review by ryonakano — APPROVED** [review]
Works on my side too. Thank you very much for your fix! :tada:

**Comment by peteruithoven** [comment]
Thanks for verifying and the great app in general :slightly_smiling_face:

**Pull request merged**
